### ISSUE TITLE
Query Builder is not Immutable

### ISSUE THREAD

**Issue by DacioRomero** [igdb/node-apicalypse#4]
I normally set up Apicalypse with parameters like this for use with the IGDB v3 API:
```javascript
const IGDB = apicalypse({
    baseURL: "https://endpoint-alpha.igdb.com",
    headers: {
        'Accept': 'application/json',
        'user-key': process.env.IGDB_API_KEY
    },
    responseType: 'json'
})
```
An issue arises when building multiple requests off of that because the query builder methods aren't immutable. This results  in new queries to "inherit" previous calls built off of `IGDB` messing up the results of the request.

Temporarily we can create a function that returns our desired default values:
```javascript
const IGDB = () => {
    return apicalypse({
        baseURL: "https://endpoint-alpha.igdb.com",
        headers: {
            'Accept': 'application/json',
            'user-key': process.env.IGDB_API_KEY
        },
        responseType: 'json'
    });
}
```

In the long-term I think it would be benficial for the query builder methods to be immutable.

Perhaps something similar to [pypika's solution](https://github.com/kayak/pypika/blob/789e7a336dd7aed77fc86205f0681319efe83477/pypika/utils.py#L35) (although a different language) of a decorator could be used?

**Comment by krazyjakee** [comment]
Good catch!
How could we change the return value of this function to achieve immutability?

https://github.com/igdb/node-apicalypse/blob/master/src/index.js#L103

**Comment by krazyjakee** [comment]
Scrap that. axios.create gives a new instance, so this should fix it.

https://github.com/igdb/node-apicalypse/blob/dev/src/index.js#L88

@DacioRomero can you test this in your use case?

**Comment by DacioRomero** [comment]
Sorry for the massive delay in communication.

I updated my server to use the released versions of APICalypse and IGDB v3 API.

I'll update you in a week or so if that helped.

**Comment by krazyjakee** [comment]
@DacioRomero I ran into the same bug myself and can confirm the change worked. Thank you very much for reporting this! I'm gonna cut a new version now.

**Comment by krazyjakee** [comment]
some more info https://github.com/axios/axios/issues/1522

**Comment by krazyjakee** [comment]
Found other cases https://github.com/axios/axios/issues/1383
