### ISSUE TITLE
When sorting null values are considered infinite

### ISSUE THREAD

**Issue by TheOddler** [igdb/node-apicalypse#7]
When sorting a column, null values in that column are considered infinite. So when using `sort ... desc` these null values will be return first.

This is similar to how SQL works I believe, but couldn't find a workaround for this. Is there a way to always have null values last?

**Comment by krazyjakee** [comment]
This is not really an issue with this wrapper but for IGDB API that feature is not currently available but is in our current sprint so ETA next friday.
